### ISSUE TITLE
except when devices are offline

### ISSUE THREAD

**Issue by MirkoDziadzka** [MirkoDziadzka/bitbar-plugin-fritzhome#5]
# how to reproduce

remove one device from power, check the output from fritzhome
# expected result

should show the device as offline
# actual result

got error message

```
Traceback (most recent call last):
  File "./fritzhome.1m.py", line 94, in <module>
    main()
  File "./fritzhome.1m.py", line 76, in main
    total_power += power
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by MirkoDziadzka** [comment]
closed by 4e12bf5
